### ISSUE TITLE
if some boolean property is `true` by default, there is no way to set it to `false` in the UI

### ISSUE THREAD

**Issue by theorlovsky** [iguissouma/nx-console-idea-plugin#102]
**Describe the bug:**

If you just uncheck it, it will simply not be passed to a schematic, falling back to the default `true`

**Expected behavior:**

A property should be passed as `--property false`, because it's natural for an unchecked checkbox to have the `false` value.

**Comment by iguissouma** [comment]
Please test with the new version, when you uncheck a property with default value true it will appear with --no-property when you run the command.

**Comment by theorlovsky** [comment]
confirm, works just fine on 0.48.1, thanks 🙂
