### ISSUE TITLE
Tasks and Projects is empty

### ISSUE THREAD

**Issue by Gouigouix** [iguissouma/nx-console-idea-plugin#105]
Hello when open Nx console in Intellij 2022.2.2 RC the Tasks and Project is empty!

![image](https://user-images.githubusercontent.com/2912507/189145589-b179189c-7c6b-4d06-959d-d43653b0cfb0.png)

I have one project and one lib with two components.
The version of Nx is 14.6.5 and the set React project.

Have you the same problem ?
Thx, John.

**Comment by iguissouma** [comment]
Hello,

Just a guess maybe you open the project and `nx.json` is not on the root folder of project.
Try to open the `orxapi.widgets` folder as a project.

**Comment by Gouigouix** [comment]
Hi iguissouma,

Thanks for the information, now it works! As I created a project on Gitlab and cloned it locally I find myself with a parent directory! 

When you apply the command `npx create-nx-workspace@latest` to create the workspace it adds a subdirectory, it's not great. It is not possible to create a workspace with content in it, there is an error when creating the workspace.

The solution is to create locally the workspace and to connect it to the gitlab repo.

Nice tool 😉
