### ISSUE TITLE
2022.3 EAP

### ISSUE THREAD

**Issue by Gouigouix** [iguissouma/nx-console-idea-plugin#109]
Hi,
Is there an update planned for the 2022.3 EAP version ?

Thx

**Comment by iguissouma** [comment]
Hello,
I pushed a new version 0.49.1 that support  the 2022.3 EAP version.
you are welcome to test it.

**Comment by Gouigouix** [comment]
Hello @iguissouma 

I tested it and it works well, thank you.

With new UI 😁
![image](https://user-images.githubusercontent.com/2912507/193225295-3687df50-32d3-47c5-b9e0-963e5a295f32.png)
