### ISSUE TITLE
Feature request: Filter options in generate list (Quality of life improvement suggestion)

### ISSUE THREAD

**Issue by petterhoel** [iguissouma/nx-console-idea-plugin#117]
Is there a way to filter away options here, or configure the ones I need?  

Use case: I usually only need a hand full, and parsing and scrolling through everything is a little painful. The best would be showing just the ones I need with a **_see all_** expander button for those times one needs something not in the short list. 
![image](https://user-images.githubusercontent.com/1263775/200764953-8ff94e72-7141-4b99-a498-94a51196dcdb.png)

**Comment by iguissouma** [comment]
Please check in the advanced settings sections, you can exclude using patterns...

<img width="1094" alt="Screenshot 2022-11-09 at 15 07 05" src="https://user-images.githubusercontent.com/9085108/200851647-1469bbe3-1e55-4236-8680-0c6538c366fd.png">

**Comment by petterhoel** [comment]
Already there, perfect! Thanks 🙏
