### ISSUE TITLE
After removing the workspace.json the plugin fails to run the correct commands

### ISSUE THREAD

**Issue by Hypenate** [iguissouma/nx-console-idea-plugin#118]
**Describe the bug:**
We have removed the workspace.json file and created separate project.json files for each project.

eg: 
```
{
"name": "sdc-portal",
...
}
```

But it shows this error:
![image](https://user-images.githubusercontent.com/7478681/201611577-b2c32137-d0ed-45df-9630-a7817e01cf10.png)

The correct command in this case would be
`nx run sdc-portal-e2e:e2e`

**Expected behavior:**
That it runs correctly like before 😆
When I use VS Code, it does work correctly.

**Comment by iguissouma** [comment]
Hello,
Thank you for reporting this issue.
The plugin take the name of app or lib from the `name` property in `package.json` (sdc-portal)
The executed command should be `nx run sdc-portal:e2e`
Did you restart IDE and reopened project?
Does the folder name is `sdc-portal-e2e`?

I will see how it's implemented on vscode .

**Comment by Hypenate** [comment]
Correct, it's an app.
We use nx `run sdc-portal-e2e:e2e`, I'm not sure why.
I did restart the IDE etc etc, removed nx-cache, node_modules,...

The folder structure is:
`C:\git\apps\sdc\portal-e2e` for cypress
and
`C:\git\apps\sdc\portal` for the app

Below is a screenshot from your awesome plugin, next to it is how it used to be:
![image](https://user-images.githubusercontent.com/7478681/201639153-d790190f-0b4c-40cc-9796-63fd03328807.png)

**Comment by iguissouma** [comment]
It seems I'm taken the folder name(containing project.json or package.json) as project name, seems not correct.
Maybe I should get the name from file and fallback to folder name.

**Comment by iguissouma** [comment]
Can you please test with this version?
> Install Plugin from disk

[Nx Console Idea-0.51.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/10006364/Nx.Console.Idea-0.51.0.zip)

**Comment by Hypenate** [comment]
Thank you for this quick update! This fixes the issue 🥳.

The names in the sidebar are now correct again, and the commands run as  expected.
Thank you very much!
