### ISSUE TITLE
Add support for local plugins

### ISSUE THREAD

**Issue by theorlovsky** [iguissouma/nx-console-idea-plugin#120]
**Describe the bug:**

When you write your custom generators in a local plugin like described [here](https://nx.dev/recipes/generators/local-generators), they're not present in the Nx Console.

**Steps to reproduce:**

**Expected behavior:**

Local plugins should be automatically detected, or there are should be the ability to add them manually via some settings menu.

**Additional context:**

**Comment by iguissouma** [comment]
Hello @theorlovsky 
Thank you for reporting this issue.
I will ship this fix on next version

<img width="1175" alt="Screenshot 2022-11-18 at 20 55 35" src="https://user-images.githubusercontent.com/9085108/202792207-a8fe9255-86ee-427f-b7fb-f0531688740e.png">

Can you try to test with this new version:
[Nx Console Idea-0.52.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/10044482/Nx.Console.Idea-0.52.0.zip)

**Comment by theorlovsky** [comment]
@iguissouma yep, it does work, thanks!
