### ISSUE TITLE
Add possibility to specify environment variables for each configuration

### ISSUE THREAD

**Issue by pavel-luhin** [iguissouma/nx-console-idea-plugin#13]
Hi all. Is there any way to specify env vars for each NX configuration in idea's 'Edit Configurations'?

**Comment by iguissouma** [comment]
Hi, I will add environment field to the run configuration on the next version.

**Comment by iguissouma** [comment]
A fileld like below, like one used on npm run Configuration?
<img width="742" alt="Screenshot 2021-01-26 at 17 51 45" src="https://user-images.githubusercontent.com/9085108/105876371-337c1080-5fff-11eb-9523-9a3cb91b9e44.png">

**Comment by pavel-luhin** [comment]
Yeah, this would be great. Thanks a lot. When are you planning to do next release?

**Comment by iguissouma** [comment]
You can try this new version, it will be available on the marketplace soon.
Install plugin from disk> choose the zip file
[Nx Console Idea-0.18.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/5875762/Nx.Console.Idea-0.18.0.zip)

**Comment by pavel-luhin** [comment]
Thanks

**Comment by iguissouma** [comment]
You are welcome, let me know if it's working as expected.
