### ISSUE TITLE
Missing Angular generators

### ISSUE THREAD

**Issue by richardsengers** [iguissouma/nx-console-idea-plugin#137]
Hi,
I'm missing a lot of generators in the dropdown like module, service, pipe etc
Does anybody know what I'm doing wrong or is it a bug?
<img width="427" alt="missing" src="https://user-images.githubusercontent.com/810038/214069950-e18ec583-82e9-4843-b27c-bda8d00afd2f.PNG">

I've don't have any exclusions:
<img width="685" alt="exclude" src="https://user-images.githubusercontent.com/810038/214070348-3797c1bc-0c15-47c6-825b-461b8bbba903.PNG">

**Comment by iguissouma** [comment]
Hello 
Thank you for reporting this.
can you provide a simple repo with same deps that you are you using? 
I will take a look to this issue.

**Comment by richardsengers** [comment]
Sure,

https://github.com/richardsengers/nx-console.test


its just an init from nx

Webstorm 2022.3.1
Build #WS-223.8214.51, built on December 20, 2022
nx console version: 0.53.0
nx version: 15.6.2

**Comment by iguissouma** [comment]
Thank you I see the problem, will be fixed on the next version.
<img width="1115" alt="Screenshot 2023-01-26 at 21 42 45" src="https://user-images.githubusercontent.com/9085108/214946372-cc86df2e-827e-4d42-a290-b5c518b9125e.png">

**Comment by richardsengers** [comment]
Hi @iguissouma ,
This is still a problem with pnpm install...do you have any idea what's causing the problem?
Everything works like expected with npm install, but with pnpm install i'm still missing a lot of generators

**Comment by iguissouma** [comment]
@richardsengers 
I'm not familiar with pnpm but will check if in node_modules there's the angular schematics.

**Comment by richardsengers** [comment]
@iguissouma I don't think it's a bug within your plugin.
For some reason the @schematics folder is missing in node_modules when installing with pnpm.
To fix this issue I've created a new nx workspace with yarn and copied the @schematics folder to the node_moduels folder. Now everything works fine
