### ISSUE TITLE
Search for Nx Generate (UI) menu 

### ISSUE THREAD

**Issue by AliYusuf95** [iguissouma/nx-console-idea-plugin#14]
Currently, I have a very long list of generators (_schematics_), it would be easier if we can search from the list

![image](https://user-images.githubusercontent.com/17704100/105949052-23a31180-607d-11eb-9c04-1eaadc52c901.png)

I think something similar to the angular generator popup would be more appropriate

![image](https://user-images.githubusercontent.com/17704100/105948878-ceff9680-607c-11eb-9e1b-422fbfe86174.png)

**Comment by iguissouma** [comment]
Yes we can implemented like the angular generator.

But if you are using keyboards, you can have similar experience.
cmd+n > Nx Generate Ui > start typing, the lis will be filtered
<img width="791" alt="Screenshot 2021-01-27 at 09 27 38" src="https://user-images.githubusercontent.com/9085108/105964002-eee58900-6081-11eb-89e8-d3a0e53071ed.png">

or 
 you can use cmd+shif+a > Nx Generaate Ui >  start typing, the lis will be filtered

<img width="671" alt="Screenshot 2021-01-27 at 09 29 34" src="https://user-images.githubusercontent.com/9085108/105964268-3ec45000-6082-11eb-9ecf-257bec66cd2d.png">

<img width="660" alt="Screenshot 2021-01-27 at 09 29 48" src="https://user-images.githubusercontent.com/9085108/105964282-44219a80-6082-11eb-8e19-6a0dc6e636b7.png">

Let me know if this satisfy your needs.

**Comment by AliYusuf95** [comment]
I think that's fine, thank you 👍

**Comment by iguissouma** [comment]
Thank you for commenting other issues.
