### ISSUE TITLE
hope can do not require `AngularJS` as enable

### ISSUE THREAD

**Issue by bluelovers** [iguissouma/nx-console-idea-plugin#15]
![image](https://user-images.githubusercontent.com/167966/107295398-3ddfe500-6aaa-11eb-96de-cdbb02db94bc.png)

https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html?from=jetbrains.org#optional-plugin-dependencies

**Comment by iguissouma** [comment]
Hello, maybe I can get rid of this dependency completely!

**Comment by iguissouma** [comment]
You can try this build.
Install the Plugin from Disk> choose the zip file.

[Nx Console Idea-0.20.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/5952654/Nx.Console.Idea-0.20.0.zip)

**Comment by iguissouma** [comment]
fixed in version 0.20.0
