### ISSUE TITLE
Suggestion: Show nx projects like gradle

### ISSUE THREAD

**Issue by pavel-luhin** [iguissouma/nx-console-idea-plugin#20]
Hi. I really like your plugin and I have some suggestions for bottom projects list:
1. Make projects groupping by directory, like it is done in gradle. Currently I have about 20 microservices (and they are increasing) and sometimes it is not comfortable to use flat view.
2. Move libs to separate tab or group them inside libs block, not to show with apps.
3. Add global tasks for all nx projects (build and tests, separate for apps and libs). Sometimes I have to run tests across all apps and it is not good to run all of them separatelly.

**Comment by iguissouma** [comment]
check a preview here
![Kapture 2021-04-07 at 21 21 41](https://user-images.githubusercontent.com/9085108/114067718-69f6c700-989d-11eb-8cbe-be990816eec2.gif)

**Comment by pavel-luhin** [comment]
Wow, that's interesting :)

I like it

**Comment by pavel-luhin** [comment]
Sorry. Misclicked :)

**Comment by iguissouma** [comment]
can you provide a screenshot please?

**Comment by pavel-luhin** [comment]
Here it is

![image](https://user-images.githubusercontent.com/8158004/114305212-c47f6580-9adf-11eb-9e69-db00e51c4fd1.png)

**Comment by iguissouma** [comment]
What WebStorm version are you using?

**Comment by iguissouma** [comment]
make sure show toolbar is checked!
<img width="591" alt="Screenshot 2021-04-11 at 17 55 47" src="https://user-images.githubusercontent.com/9085108/114311482-3c08c100-9aef-11eb-9c1e-0b6f04a51374.png">

**Comment by pavel-luhin** [comment]
Oh, thank you, it works now.

**Comment by pavel-luhin** [comment]
Hi. I thought about two more things:
1. Add please possibility to open tasks when double click on project, not only when clicking arrows.
2. Maybe think about adding automatically to run configuration when build test or serve task was run, like it is done in Gradle plugin.

**Comment by pavel-luhin** [comment]
Looks good. thank you!
