### ISSUE TITLE
Add configurations to the project tree

### ISSUE THREAD

**Issue by peterreisz** [iguissouma/nx-console-idea-plugin#24]
It's already exists in the vscode nx plugin, but it would be great to have this feature here too:

![image](https://user-images.githubusercontent.com/11595433/118011631-8ed4d300-b350-11eb-97f5-419f0422839c.png)

**Comment by iguissouma** [comment]
Yes that's a feature, I wanted to add.

**Comment by iguissouma** [comment]
What do you think of an implementation like this?  it's more simple than grouping on a new tree node!

<img width="702" alt="Screenshot 2021-05-16 at 20 40 24" src="https://user-images.githubusercontent.com/9085108/118408851-9fa28300-b687-11eb-90ae-0327412d71e8.png">

**Comment by peterreisz** [comment]
Like it, thanks!

**Comment by iguissouma** [comment]
The feature is available in the version 0.26
You can also run from `workspace.json` or `angular.json` file too.

<img width="576" alt="Screenshot 2021-05-21 at 10 20 59" src="https://user-images.githubusercontent.com/9085108/119106316-83ec0380-ba1e-11eb-9cb7-d60df85b620b.png">

**Comment by peterreisz** [comment]
Tried it, works fine, thanks!
