### ISSUE TITLE
Creating new "Nx Workspace" project not longer working

### ISSUE THREAD

**Issue by pawelkielb** [iguissouma/nx-console-idea-plugin#25]
### Steps to reproduce
1. `File > New > Project`
2. Select "Nx Workspace"
3. Click **Next** and then **Finish**
4. Select empty template and skip rest of the prompts

You will get:
`Nx failed to create a workspace.`

and logs'll say:

`[project directory] is not an empty directory.`

**Comment by iguissouma** [comment]
I produce the problem, I will try to fix it.

**Comment by iguissouma** [comment]
Sorry for the delay to fix this issue but it should be fixed in this version 0.36.0.
