### ISSUE TITLE
Plugin is incompatible with IDE build 211.*+

### ISSUE THREAD

**Issue by JimMorrison723** [iguissouma/nx-console-idea-plugin#26]
Hi,
I am currently using : WebStorm 2021.2 EAP Build #WS-212.4037.16, built on June 8, 2021
But i am unable to use this great plugin, because: 
![image](https://user-images.githubusercontent.com/506946/122010207-2c417d80-cdbb-11eb-82ea-fafe0430a970.png)

It would be nice if you could update the plugin, so EAP users can continue using it!

**Comment by iguissouma** [comment]
Hello,
I pushed a new version 0.27.0, should allow use of EAP version.

**Comment by JimMorrison723** [comment]
Thank you for the super quick update, it is working now again!
