### ISSUE TITLE
Support standaloneConfigs

### ISSUE THREAD

**Issue by nidomiro** [iguissouma/nx-console-idea-plugin#27]
To avoid a huge workspace.json/angular.json we want to use standaloneConfigs: https://nx.dev/latest/angular/core-concepts/configuration#projectjson

Currently the Plugin does not support this and stops working at all.

You can find an example repo here: https://github.com/nidomiro/nx-standalone-config-example

**Comment by nidomiro** [comment]
The newest update works, thanks 😊

**Comment by iguissouma** [comment]
You are welcome.
