### ISSUE TITLE
Feature request - Ability to filter out the generation list

### ISSUE THREAD

**Issue by vitalybe** [iguissouma/nx-console-idea-plugin#30]
![image](https://user-images.githubusercontent.com/1933752/127290011-eb217ce9-1722-48da-bdaa-f8189a6a8d4e.png)

Right now many of the generators I see here are not relevant. I can get around it by using some prefix and filtering but it would be nice if I could choose which packages I want to see generators from or some other form of "pre-filtering"

**Comment by iguissouma** [comment]
I will take a look.

**Comment by scomans** [comment]
It would be great too if `Nx Generate (UI)...` in the `New` context menu would open the popup and not the list. Otherwise you have to scroll through the complete list as workspace-schematics are at the bottom and there is no way to filter there.

**Comment by vitalybe** [comment]
@scomans This is actually already possible today. Simply make a keyboard binding to "Nx Generate (UI)". Select a folder/file and press the shortcut.

You can then type to search the list, no need to scroll.

**Comment by scomans** [comment]
Thank you for this tip. But the issue remains for the context menu. It's not really usable in this state.

**Comment by iguissouma** [comment]
@scomans Thanks for your feedback.
I'm open to any enhancement.
What you want is something similar to the angular generator popup?
Here a discussion about a similar issue:
https://github.com/iguissouma/nx-console-idea-plugin/issues/14

**Comment by scomans** [comment]
A popup would be ideal. A popup might also fix the 10sec freeze I get when I open the `New` menu. There are simply too many entries.

**Comment by iguissouma** [comment]
You can use this setting to exclude generators:
 
<img width="976" alt="Screenshot 2022-05-28 at 11 37 56" src="https://user-images.githubusercontent.com/9085108/170819871-82438274-5bfa-4b81-914a-73cd7231fe5a.png">
