### ISSUE TITLE
Feature request - Focus on project

### ISSUE THREAD

**Issue by vitalybe** [iguissouma/nx-console-idea-plugin#31]
I really like the ability to load/unload projects ("NX load/unload apps and libs), and the way it also loads/unloads dependencies of the project.

I thought that it'd be nice to take it one step forward - An easy way to "focus" on a single project. It would work like so:

- User would choose a project to focus on from right-click context menu (or from a filterable popup)
- All unrelated projects/libraries would unload. All related ones would be loaded.
- You'll have an ability to see/run the tasks only of the focused project

How does that sound?

**Comment by iguissouma** [comment]
I will see what I can do.

**Comment by iguissouma** [comment]
I did some work. This is how it will looks.
https://mobile.twitter.com/iguissouma/status/1422962363515510784

**Comment by vitalybe** [comment]
Awesome! Looks like exactly what I was talking about, thanks!

**Comment by vitalybe** [comment]
Just something to consider - Besides an ability to do it from the context menu, it'd be great if I can also open it from a keyboard-friendly action dropdown. Something like "Recent Files"/"Recent Project"
