### ISSUE TITLE
Cannot recognize an external command

### ISSUE THREAD

**Issue by constantant** [iguissouma/nx-console-idea-plugin#39]
![nx-plugin-issue](https://user-images.githubusercontent.com/5537730/134825191-9a8571eb-7d55-48f1-96e8-576c29a46c2a.gif)

```
"C:\Program Files\nodejs\node.exe" C:\Users\user\projects\nx-svelte-manual\node_modules\@nrwl\cli\bin\nx.js run memory-cards:serve

> nx run memory-cards:serve 
'svelte-kit' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Something went wrong in @nrwl/run-commands - Command failed: svelte-kit dev

———————————————————————————————————————————————

>  NX   ERROR  Running target "memory-cards:serve" failed

  Failed tasks:

  - memory-cards:serve

  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/Qb4i8lioER4


Process finished with exit code 1

```

But in case I run `nx run memory-cards:serve` directedly from ci it works as expected 

Logs:
[webstorm-logs-20210926-234633.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/7232311/webstorm-logs-20210926-234633.zip)

**Comment by iguissouma** [comment]
When you run on cli it's working?
Can you share a simple project on github?

**Comment by constantant** [comment]
@iguissouma here you are https://github.com/constantant/memory-cards/tree/sveltekit

**Comment by iguissouma** [comment]
Thank you for the repo.
I figured out how to fix it, I will push a fix soon.
<img width="1069" alt="Screenshot 2021-09-28 at 22 16 55" src="https://user-images.githubusercontent.com/9085108/135160266-bc743656-8d8c-4ae9-8f51-4ec5972f8c3b.png">

As a workaround you can add `<nx-workspace-dir>/node_modules/.bin` to the PATH variable environment.

**Comment by iguissouma** [comment]
Please try the latest version (0.32.1) if it fixes the issue.

**Comment by constantant** [comment]
@iguissouma it works now as expected!
