### ISSUE TITLE
Does not work with workspace.json

### ISSUE THREAD

**Issue by pf1gura** [iguissouma/nx-console-idea-plugin#4]
When project uses `workspace.json` files nothing seems to work. Projects and tasks list does not load, refactoring feature (move lib) does not open, etc.

When I change `workspace.json` to `angular.json` everything seems to be working just fine.

Steps to reproduce
* create new nx workspace with non-angular preset (using nx cli)
* open it in IntelliJ IDE

**Comment by iguissouma** [comment]
Yes, the plugin does not support the `workspace.json` file.
I just added the support it will be available on the next version `0.9.0`.

<img width="1150" alt="Screenshot 2020-11-09 at 20 43 27" src="https://user-images.githubusercontent.com/9085108/98588819-9b5a6f00-22cc-11eb-85fa-828cada101e9.png">

**Comment by pf1gura** [comment]
That is great. Thank you for a quick response. Looking forward to testing new version!
