### ISSUE TITLE
Setting `default` to `true` will omit parameter when checkbox not checked

### ISSUE THREAD

**Issue by scomans** [iguissouma/nx-console-idea-plugin#40]
When a property has a default value of `true` and the `boolean` type the generated command will not have the parameter when the checkbox is not checked. The result will be a `true` value for the generator and therefore the complete opposite of what the user selected.

The following property
```
    "dataloader": {
      "description": "Wheather a dataloader will be generated.",
      "type": "boolean",
      "default": true
    }
```
![image](https://user-images.githubusercontent.com/631504/134916517-f913f244-ffc3-4d9f-bb44-6675c11cb451.png)
will result in
```
"C:\Program Files\nodejs\node.exe" C:\Users\user\project\node_modules\@nrwl\cli\bin\nx.js workspace-schematic nestjs-graphql-resolver --name=test --project=test --path=libs/service/test/src/lib/test
```
but should be
```
"C:\Program Files\nodejs\node.exe" C:\Users\user\project\node_modules\@nrwl\cli\bin\nx.js workspace-schematic nestjs-graphql-resolver --name=test --project=test --path=libs/service/test/src/lib/test -dataloader=false
```

**Comment by iguissouma** [comment]
Hello,
Thanks for reporting this.
I see the problem, I will try to fix this ASAP.

**Comment by scomans** [comment]
I will try to create a repo later today.

But I tested the command you provided and the `--no-dataloader` parameter seems to work

**Comment by iguissouma** [comment]
The equivalent of this plugin is [Nx Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console).

I will try to fix this issue.

**Comment by iguissouma** [comment]
Please try the latest version (0.32.1) if it fixes the issue.

**Comment by scomans** [comment]
It works like a charm now. Thank you very much!
