### ISSUE TITLE
Collection "@schematics/angular" cannot be resolved. 

### ISSUE THREAD

**Issue by solshark** [iguissouma/nx-console-idea-plugin#41]
I've created new project using following command:
`pnpx create-nx-workspace --package-manager=pnpm`
<img width="1278" alt="133427218-6631b63d-0ab4-4319-9a10-65294284027f" src="https://user-images.githubusercontent.com/107233/135256726-b5572f18-dc0d-498d-986d-87ba70893045.png">
Next, trying to generate new library using plugin for WebStorm:

<img width="1605" alt="133427732-1a786b5e-34f1-459a-ab43-b0449702810b" src="https://user-images.githubusercontent.com/107233/135257013-eb35115d-d2da-43f2-93be-c2f0faac2089.png">

git@github.com:solshark/i6820.git

Generation directly via command line works fine.

Both Webstorm and plugin of most recent versions.

**Comment by iguissouma** [comment]
I tested on my Env it's working.
I don't know what's wrong, maybe you are using nvm but it should be the same.

<img width="1080" alt="Screenshot 2021-09-29 at 14 54 34" src="https://user-images.githubusercontent.com/9085108/135272445-63069d2a-31af-4895-8bf7-4e5ab1def462.png">

Does it fails for all schematics?

Other feature like  build is working?

<img width="982" alt="Screenshot 2021-09-29 at 14 58 29" src="https://user-images.githubusercontent.com/9085108/135273018-a4ffbe63-f1f7-4991-a5cf-99a77124a037.png">

**Comment by solshark** [comment]
It fails only for `@nrwl/angular`
Other schematics do works fine. I do use `nvm` and `pnpm`

**Comment by iguissouma** [comment]
Sorry, but I can't reproduce the problem and I have no idea what is the issue.

**Comment by solshark** [comment]
Could I do anything to help?

**Comment by iguissouma** [comment]
Sorry for the delay!

vscode is working or failing?

A command like this will works or give you an error?
without exec:
/Users/iguissouma/.nvm/versions/node/v16.11.0/bin/node /usr/local/lib/node_modules/pnpm/bin/pnpm.cjs nx generate @nrwl/angular:library --name=shared/ui --dry-run --no-interactive

with exec:
/Users/iguissouma/.nvm/versions/node/v16.11.0/bin/node /usr/local/lib/node_modules/pnpm/bin/pnpm.cjs exec nx generate @nrwl/angular:library --name=shared/ui --dry-run --no-interactive


I will try a configuration so you can select the package manager you want to use.

<img width="1398" alt="Screenshot 2021-10-31 at 12 25 14" src="https://user-images.githubusercontent.com/9085108/139580862-9a749c80-557c-421a-b6ce-d8d2baa42dba.png">

**Comment by iguissouma** [comment]
@solshark can you test with the latest version of plugin?

**Comment by solshark** [comment]
It works, thx.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
