### ISSUE TITLE
Translation missing for "nx.notifications.balloon"

### ISSUE THREAD

**Issue by bennycode** [iguissouma/nx-console-idea-plugin#49]
I clicked on "Nx Migrate Workspace" from the "Event Log" and saw in the "Notifications" (when it failed) that there is a missing translation.

![image](https://user-images.githubusercontent.com/469989/145855052-0caaee45-5f1c-48e1-be9a-b7a02a9e1168.png)

**Comment by iguissouma** [comment]
Thank you for reporting this.
I will fix it.

**Comment by bennycode** [comment]
Thank you for taking care of it. Your plugin improves my workflow. 👍

**Comment by iguissouma** [comment]
Should be resolved on latest version 0.46.0
