### ISSUE TITLE
[WSL] Cannot run nx commands from the editor pane

### ISSUE THREAD

**Issue by Rigellute** [iguissouma/nx-console-idea-plugin#52]
Plugin Version: 0.35.0

When the project is in the Windows Subsystem for Linux, trying to run nx commands from the editor pain results in the error
```
Process finished with exit code 11
```

For clarity, I mean clicking on the green play icon and pressing run or using the shortcut `Ctrl + Shift + F10` (see below)

![image](https://user-images.githubusercontent.com/12150276/148196935-a57d350a-1ad2-4b24-964f-dc2631f56747.png)

I can't find any logs to reveal more about why this is failing but happy to help debug this.

**Comment by iguissouma** [comment]
Hello,

Can you provide the hole console output?
I need to look on nodejs wsl and Intellij integration.
Does npm run scripts from `package.json` works for you, I mean the green play icon?

**Comment by iguissouma** [comment]
I will take a look how its works for package.json, should be similar.
Will take some time I’m on vacation for two weeks.

**Comment by Rigellute** [comment]
Thanks @iguissouma , hope you have a good vacation! And thanks for making this plugin

**Comment by iguissouma** [comment]
Hello 

[Nx Console Idea-0.39.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8148658/Nx.Console.Idea-0.39.0.zip)

can you try this version? 
I wasn't able to test on wsl environment!

Install plugin from disk > choose the zip file.

**Comment by creaux** [comment]
Same issue.

**Comment by iguissouma** [comment]
Hello,

Never used Jetbrains IDE with wsl and nodejs, Are you able to run npm start with run configuration on wsl environment?

<img width="895" alt="Screenshot 2022-03-06 at 21 15 05" src="https://user-images.githubusercontent.com/9085108/156940581-490ee26c-2eff-4c15-8a09-b605891de731.png">

Can you  show me your run configuration of npm and the console output (the first lines...)?

<img width="1012" alt="Screenshot 2022-03-06 at 21 20 40" src="https://user-images.githubusercontent.com/9085108/156940725-78020e86-b58d-418b-9c56-03f702cb18c3.png">

**Comment by NorthwooDzp** [comment]
I have the same issue, comand is 
C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/sh -c "cd /home/user/Projects/test-project && /usr/bin/node /home/user/Projects/test-project/node_modules/@nrwl/cli/bin/nx.js run 'serve:development'"

if I copy this command and run in windows terminal (powershell) or even in cmd it will work

btw on windows 11 I didn't have this error (don't know why)

**Comment by creaux** [comment]
Hi @iguissouma,

here you go:

![image](https://user-images.githubusercontent.com/1745028/158029240-1322077a-deb9-4381-b48a-ef1aa3e35af5.png)

**Comment by iguissouma** [comment]
@creaux @NorthwooDzp Thanks for your reply.
I figured how it should works.
It should works on v0.39.
One thing is still not working is adding node_modules/bin to the PATH environment variable.

<img width="803" alt="2022-03-13_20h32_30" src="https://user-images.githubusercontent.com/9085108/158076025-7645db52-75ae-4b2e-8bc0-d6b1a9468c81.png">

**Comment by NorthwooDzp** [comment]
@iguissouma thank you for your reply, I've updated version and now I see this error
![image](https://user-images.githubusercontent.com/25038856/158129798-d2a62332-090d-47cc-bce3-4d39ea271bc8.png)

**Comment by iguissouma** [comment]
@NorthwooDzp 
I'm not sure why your reply doesn't appear here.

But for your error make sure you select the package manager the one without \\wsl$ path
see settings> Languages & frameworks > Nodejs

Delete already created Nx run configuration and try again.

**Comment by NorthwooDzp** [comment]
Hi @iguissouma , my reply does not appear because I removed it after I set right npm for project. Thank you, everything works properly.

**Comment by NorthwooDzp** [comment]
Hi @iguissouma, problem with WSL is back in version 0.40.0

**Comment by iguissouma** [comment]
Please try new version 0.41
