### ISSUE TITLE
Two nx tool windows with the same name

### ISSUE THREAD

**Issue by nidomiro** [iguissouma/nx-console-idea-plugin#6]
I want to use the keyboard more often. But I encountered the problem, that the nx-scematics and the nx-run dialog are both named nx. Therefore I can only differentiate the two by their location in the IDE which requires me to use the mouse.

Is it possible to give them a different name? like "nx: run" and "nx: gen"

![image](https://user-images.githubusercontent.com/15079172/101196305-d8faaf80-3660-11eb-8e2f-3697445e3de1.png)

**Comment by iguissouma** [comment]
Hello, maybe you have installed the two available plugins, nx-webstorm(nx generate) and Nx Console Idea(nx run).
Nx Console Idea provide nx generate integration not in a tool window.

Using nx generate in Nx Console Idea
Open The Run Anything popup opens.
Type nx generate in the search field. As you type, WebStorm shows the matching tasks. Select the required one from the list and press ⏎.
<img width="671" alt="Screenshot 2020-12-03 at 11 01 27" src="https://user-images.githubusercontent.com/9085108/101209103-7fe84700-3673-11eb-9fcd-1b8ae585f022.png">

Webstorm will suggest options of selected schematic for your command
 
<img width="670" alt="Screenshot 2020-12-03 at 11 05 12" src="https://user-images.githubusercontent.com/9085108/101209128-8ecef980-3673-11eb-8ec1-938e5c6f7b28.png">

 
you can switch to ui mode anytime by adding --ui option (doesn’t appear as options)
<img width="672" alt="Screenshot 2020-12-03 at 11 15 05" src="https://user-images.githubusercontent.com/9085108/101209161-9ee6d900-3673-11eb-9e41-64a276efaca7.png">


In the editor a UI with the selected schematic will appear. You can fill the options and do a run or dryRun 

 
<img width="822" alt="Screenshot 2020-12-03 at 11 28 27" src="https://user-images.githubusercontent.com/9085108/101209234-b58d3000-3673-11eb-9ef5-fe4d971ed208.png">

 
 
Generate ui can be shown by right clicking in the explorer context menu. the path you click on will be used as a value for the "path" option.

 
<img width="1047" alt="Screenshot 2020-12-03 at 11 40 36" src="https://user-images.githubusercontent.com/9085108/101209255-be7e0180-3673-11eb-83f9-d14acc23bae7.png">

**Comment by nidomiro** [comment]
You are absolutely right, thanks for the clarification :)
