### ISSUE TITLE
Not compatible with IntelliJ IDEA 2022.1

### ISSUE THREAD

**Issue by m-evasys** [iguissouma/nx-console-idea-plugin#68]
The plugin is not compatible with the latest IntelliJ IDEA 2022.1 Version.

**Comment by iguissouma** [comment]
Please try new version Nx Console Idea 0.40.0.
Should be compatible with the latest IntelliJ IDEA 2022.1 Version.

**Comment by eliotis** [comment]
Thanks bro!
