### ISSUE TITLE
Error when running commands via Nx Console UI

### ISSUE THREAD

**Issue by mattndr** [iguissouma/nx-console-idea-plugin#69]
Nx Console Idea 0.40.0
WebStorm 2022.1

With the latest WebStorm version, if I try to run a command via the Nx plugin UI, I get this error:

![Screenshot from 2022-04-13 00-38-56](https://user-images.githubusercontent.com/85292022/163066194-307380fd-7e06-4b60-ab17-75e0bbeb1b7e.png)

Paths: 

![Screenshot from 2022-04-13 00-38-19](https://user-images.githubusercontent.com/85292022/163066190-292bdb49-8ddc-4e7b-a0e4-d4cb8e69b2a5.png)

**Comment by iguissouma** [comment]
Hello,
Thanks for reporting this issue.

You can try to use npm package manager as a workaround.

<img width="712" alt="Screenshot 2022-04-13 at 04 49 43" src="https://user-images.githubusercontent.com/9085108/163090494-b9c35a66-3c7a-427a-b18a-4f683296a212.png">

I think it can be specify in your project by default here:
<img width="895" alt="Screenshot 2022-04-13 at 04 53 18" src="https://user-images.githubusercontent.com/9085108/163090694-07330c6e-a84e-49a3-9026-482685d60b61.png">

**Comment by dimd13** [comment]
Hello, i have a same problem with yarn 
```
Specify a valid package manager: cannot find a binary file inside '/usr/bin/yarn' directory
```
---
Nx Console Idea 0.40.0
WebStorm 2022.1

**Comment by mattndr** [comment]
I changed the Package manager path to ```~/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm```
Now it's working.

**Comment by dimd13** [comment]
> I changed the Package manager path to `~/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm` Now it's working.

Ok, but I do not use nvm & pnpm. I completely update node & yarn, checked the paths in the settings and they are all correct, invalidate the caches in IDE, but still getting the error

**Comment by mattndr** [comment]
> > I changed the Package manager path to `~/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm` Now it's working.
> 
> Ok, but I do not use nvm & pnpm. I completely update node & yarn, checked the paths in the settings and they are all correct, invalidate the caches in IDE, but still getting the error

Your package manager path should be ``` /usr/lib/node_modules/yarn ```

**Comment by dimd13** [comment]
command ` yarn -v` says `1.22.18`
command `which yarn` says `/usr/local/bin/yarn` not `/usr/lib/node_modules/yarn` 
Ok, binary for `yarn` is at `/usr/local/lib/node_modules/yarn/bin` and i tried to specify this path in settings and still have an error
```
Specify a valid package manager: cannot find a binary file inside '/usr/local/lib/node_modules/yarn/bin/yarn' directory
```

**Comment by dimd13** [comment]
> `/usr/local/lib/node_modules/yarn/bin` seems to be the wrong path; please try specifying `/usr/local/lib/node_modules/yarn` in > _Settings | Languages & Frameworks | Node.js | Package manager_

Thank you very much, now it's worked, just fine!

**Comment by zyf0330** [comment]
I meet the same error `Specify a valid package manager: cannot find a binary file inside '/usr/bin/yarn' directory`, and it is the correct yarn binary.
![image](https://user-images.githubusercontent.com/11958657/163338194-6872db32-8ebe-47bf-8553-e0152781d45c.png)

If I specify directory `/usr/bin` of yarn binary in > Settings | Languages & Frameworks | Node.js | Package manager, nx works, but run script in the package.json doesn't work anymore. 

So I think nx plugin uses this option wrongly, should not treat it as package manager binary directory.

**Comment by zyf0330** [comment]
And why specifying npm binary works? why yarn doesn't work.

**Comment by AndyClausen** [comment]
Something broke recently. I used yarn with this plugin last week and it worked fine, now it doesn't.
Getting this similar message:
```
Specify a valid package manager: cannot find a binary file inside 'C:\Program Files\nodejs\yarn.cmd' directory
```
Other tasks, like a regular npm run task, work fine with yarn so it's something in this plugin specifically.

**Comment by iguissouma** [comment]
Yes, something changed with the latest IDE 2022 version.
I will make sure npm and nx works with similar npm configuration

**Comment by yock** [comment]
I don't mean to be a pile-on but wanted to add my configuration to this discussion. Also experiencing this error since upgrading to Rubymine 2022.1 using yarn with nodenv. It's interesting that it suddenly thinks that the path to the yarn executable is a directory. Wondering if that's a clue as to what JetBrains changed. Thanks for looking into this. Happy to help anyway I can.

**Comment by iguissouma** [comment]
@yock @zyf0330 @AndyClausen @dimd13 
can you please test this version and report if is working?

[Nx Console Idea-0.42.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8624874/Nx.Console.Idea-0.42.0.zip)

**Comment by IsaacClem** [comment]
@iguissouma Works for me too! :)
