### ISSUE TITLE
Can't start "serve" in debug mode for node workspace

### ISSUE THREAD

**Issue by vanakema** [iguissouma/nx-console-idea-plugin#7]
**State of things**
in angular.json, the `serve` command has `"inspect": true` set
the project I'm trying to debug, is made from the Nx `workspace` plugin

**Issue I'm having**
I can't start a node workspace project's "serve" command in debug mode without it dying because it says "connection refused", even though the inspect flag is true. 

**Things I've tried**
I also tried making a Node.js debugger run configuration, pointing at port 7777, and it cannot connect to the Nx debug port

**Comment by iguissouma** [comment]
You want to debug the `serve` task or the served application?
If you want to debug the served angular app, follow this steps:

![Kapture 2020-10-24 at 19 48 12](https://user-images.githubusercontent.com/9085108/101534046-e4b6e080-3996-11eb-9a78-821d9fe7b9fb.gif)

**Comment by vanakema** [comment]
Thanks for the gif, I really appreciate that effort. It was very kind of you.

No, I want to debug a node app. I only mentioned angular.json because that's how Nx launches everything under the hood, and is where you put the `inspect` flag. I posted because of the existence of the "debug" option that shows up in the list when you right click the `serve` task, so I thought you might've done work to make that option work. I wanted to make sure I wasn't doing something dumb that messed up the defaults. 

Is there a way you could disable the "debug" option when you right click on the Nx task? It's a little misleading since it doesn't actually work. I've tried connecting to the node process with the debugger, but it similarly gets the connection refused issue, but I'll continue trying to get it to work from that angle. 

The issue with this route is that you can't connect to the debugger before code actually executes, so if you could get the "debug" run configuration to work as part of the plugin, that would be amazing, and would be very helpful in general to people using the plugin.

**Comment by iguissouma** [comment]
Hello,

I agree it's confusing the debug, I was thinking about it and how it should work and how it should works.
But for your case as a workaround you can debug like below.

you can add to your package.json a script will call it `debug` that run the serve

<img width="500" alt="Screenshot 2020-12-09 at 19 07 33" src="https://user-images.githubusercontent.com/9085108/101669550-5e5fd480-3a52-11eb-8b4b-fcb73f5e82d8.png">

You click on the gutter and choose `debug`
<img width="419" alt="Screenshot 2020-12-09 at 19 13 09" src="https://user-images.githubusercontent.com/9085108/101669747-99620800-3a52-11eb-9de1-86a101f58d92.png">

If you set breakpoints to your node app in my case `api` then it should works.

<img width="1190" alt="Screenshot 2020-12-09 at 19 16 08" src="https://user-images.githubusercontent.com/9085108/101670145-18efd700-3a53-11eb-841d-1838dad62cac.png">

<img width="1092" alt="Screenshot 2020-12-09 at 19 20 08" src="https://user-images.githubusercontent.com/9085108/101670547-99163c80-3a53-11eb-9659-8e304e49b585.png">

Hope this can help.

The nx run configuration is similar to npm run script configuration.
But as you can serve anything with nx(java, kotlin, go or others) it cannot be always used...

**Comment by vanakema** [comment]
Thank you so much. You've been very helpful

**Comment by iguissouma** [comment]
should be fixed in version 0.17.0
<img width="1400" alt="Screenshot 2021-01-13 at 11 26 52" src="https://user-images.githubusercontent.com/9085108/104508963-4fd48200-55e9-11eb-82d8-d1362ed7e742.png">
