### ISSUE TITLE
Nx Dep Graph projects deselect themselves

### ISSUE THREAD

**Issue by AndreasHae** [iguissouma/nx-console-idea-plugin#70]
**Steps to reproduce**

1. Open Nx Dep Graph sidepanel
2. Start server via Play button in panel
3. Select some projects
4. All projects are deselected after a few seconds

**Expected behavior**

The projects should not deselect themselves

Here's a screen recording for additional explaination
https://user-images.githubusercontent.com/14837928/164615853-b74d13ae-53d7-42c4-8b8c-a9a11cff3f5e.mov

**Versions**

* Plugin version: 0.41.0
* @nrwl/workspace: 12.10.0
* @nrwl/cli: 12.10.1

**Comment by iguissouma** [comment]
Hello, 

It's a bug in Nx Dep Graph with watch flag, try to run dep graph command with --watch flag and you shoud have same issue.
I reported this issue, maybe it was fixed in newest nx version.
