### ISSUE TITLE
UI output commands are incorrect 

### ISSUE THREAD

**Issue by mattndr** [iguissouma/nx-console-idea-plugin#71]
The UI form generates commands which params are not detected. This happens when using pnpm:
```
/home/matt/.nvm/versions/node/v16.15.0/bin/node /home/matt/.nvm/versions/node/v16.15.0/lib/node_modules/pnpm/bin/pnpm.cjs nx generate @nrwl/angular:library --name=demo --dry-run --no-interactive

> nx "generate" "@nrwl/angular:library"

✖ What name would you like to use for the library? · 
```

The command generated should follow this pattern:
```
/home/matt/.nvm/versions/node/v16.15.0/bin/node /home/matt/.nvm/versions/node/v16.15.0/lib/node_modules/pnpm/bin/pnpm.cjs nx generate @nrwl/angular:library -- --name=demo --dry-run --no-interactive
```

**Comment by iguissouma** [comment]
Hello, 
What version are you using WebStorm/Intellij, the plugin?

Why should we add -- for pnpm?

I will take a look to this issue while fixing #69

**Comment by mattndr** [comment]
Nx Console Idea 0.41.0
WebStorm 2022.1
pnpm 6.32.11

Without --, any command launched via the UI doesn't recognize the custom configurations that have been enterd, like **name** for example. Then it will ask again to enter a name for the library (as you can see in my previous post), even if I have already specified this in the UI. 
This also applies to all other configured values.

![image](https://user-images.githubusercontent.com/85292022/166335338-0be55ad2-6124-423d-a13f-853697ee6809.png)

**Comment by mattndr** [comment]
With the uploaded version everything works properly. Thanks!
