### ISSUE TITLE
Missing "root" property in project.json breaks UI

### ISSUE THREAD

**Issue by wanjas** [iguissouma/nx-console-idea-plugin#74]
Hello, I hope I'm not misunderstanding the problem. 

**Describe the bug:**
Since `nx` version 14.1.0 or so there is no more "root" property in `project.json`. 

Because of that if you try to run a command from project.json it will fail trying to run something like "npx nx run **null**:build"
On another hand running tasks from nx panel works correctly. 
(See screenshot)

If you add "root" (or bring it back after nx migration removes it) and restart IDE, UI starts to work correctly again. 

**Steps to reproduce:**
Plugin version 0.42.0. RubyMine 2022.1+

```shell
npx create-nx-workspace@latest --preset=apps no-root-nx
nx g @nrwl/node:app
```

**Expected behavior:**
"null" is a correct project name

![2022-05-17_20-14](https://user-images.githubusercontent.com/3997185/168799155-7db97778-896b-4600-8f9d-fb8d564dd2d3.png)

**Comment by iguissouma** [comment]
Yes, you are right, the missing root property in project.json leads to this behaviour.
I will try to align more with what is done for Nx Console vscode plugin.

You can add the root property manually for now.
I'm in process of rewriting the builders and executors from scratch ...
I will try to fix this issue ASAP.

**Comment by wanjas** [comment]
@iguissouma 
> You can add the root property manually for now.
Yes, it's what I'm doing as a workaround for now. 

Thank you very much!

**Comment by iguissouma** [comment]
@wanjas @NorthwooDzp can you please test this version. and report if it fixes the issue.
Thanks.

[Nx Console Idea-0.43.2.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8779261/Nx.Console.Idea-0.43.2.zip)

**Comment by NorthwooDzp** [comment]
@iguissouma works fine

**Comment by wanjas** [comment]
@iguissouma now everything works as expected. Thank you very much!
