### ISSUE TITLE
Support build 222.*

### ISSUE THREAD

**Issue by bartekczyz** [iguissouma/nx-console-idea-plugin#78]
Thank you for this amazing plugin! :) 

**Describe the bug:**

Current version is not compatible with build `222.*`

**Steps to reproduce:**

;) 

**Expected behavior:**

I would like to use the plugin in IntelliJ IDEA 2022.2 EAP

**Comment by iguissouma** [comment]
Happy you find the plugin useful.
Nx Console Idea 0.44.0 was published with support of 222.* build.

**Comment by bartekczyz** [comment]
Thank you! 🎉
