### ISSUE TITLE
Generate page is not updating

### ISSUE THREAD

**Issue by nidomiro** [iguissouma/nx-console-idea-plugin#8]
I encountered the problem, that the "Generate.nx" page is not updating the selected schematic.

**How to reproduce:**
1. Select a schematic you want to execute via the generate-item in the "new" menu.
2. Execute step 1 but select a different schematic

**Expected behaviour:**

One of the two:
1. The "Generate.nx" is updating the viewed schematic to the newly selected.
2. A new "Generate.nx" page opens with the new schematic.

**Comment by iguissouma** [comment]
Hello, 

Thanks for submitting this issue.

Yes, it's known issue, I will fix it.
Maybe I will go with option one.
