### ISSUE TITLE
Workspace level generators disappeared from schematics list

### ISSUE THREAD

**Issue by itspers** [iguissouma/nx-console-idea-plugin#82]
**Describe the bug:**
It was working fine before, but in last few weeks (i believe after one of NX updates) stopped working.

**Steps to reproduce:**
Generate generator - https://nx.dev/generators/workspace-generators#creating-a-workspace-generator

`nx generate @nrwl/workspace:workspace-generator my-generator`

**Expected behavior:**
Workspace schematic should appear in list near other schematics in generate dialog.

**Additional context:**
I works as before in VScode and this plugin https://plugins.jetbrains.com/plugin/15000-nx-webstorm (but your plugin is better)

**Comment by iguissouma** [comment]
Hello,

Thank you for reporting this issue.
Can you please test with this version (> Install plugin form Disk)?

[Nx Console Idea-0.45.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8894654/Nx.Console.Idea-0.45.0.zip)
