### ISSUE TITLE
Using a Project Node.js Remote Interpreter does not work

### ISSUE THREAD

**Issue by jpv-os** [iguissouma/nx-console-idea-plugin#90]
**Describe the bug:**
Using the plugin with a project-wide Node.js remote interpreter does not work. 

**Steps to reproduce:**

1. Configure a remote Node.js interpreter as shown in the Jetbrains docs: https://www.jetbrains.com/help/webstorm/node-with-docker.html

<img width="790" alt="Bildschirmfoto 2022-07-06 um 16 50 29" src="https://user-images.githubusercontent.com/63935349/177579862-df6e1b7f-0ec5-4902-86a6-83ecaea7063a.png">

The remote interpreter is now correctly setup and all Webstorm features work as expected (for example the `npm` run scripts)

2. Configure the nx plugin to use the project interpreter

(removed screenshot)

3. Try to generate a component using the plugin

<img width="1408" alt="Bildschirmfoto 2022-07-06 um 16 51 53" src="https://user-images.githubusercontent.com/63935349/177580161-969ea40b-3458-4ef0-9a06-1157cf26cf1c.png">

As we can see, the plugin generated a wrong command. For some reason, it adds the call to `npm` (as specified in the remote interpreter settings). Notice the `/usr/local/lib/node_modules/bin/npm-cli.js`, which is exactly the part of the command which shouldn't be there. It changes the behavior, so that instead of the `nx` command, it actually invokes `npm` and provides the rest (`nx ...`) as an argument to the `npm` call. As a result, `npm` is executed with unknown arguments and the usage message appears.

4. To verify this, I experimented with the project remote interpreter settings and cleared the `npm` input field

(removed screenshot)

My hope was that the plugin now pastes an empty string in the command and it would actually work. And indeed, it works:

<img width="988" alt="Bildschirmfoto 2022-07-06 um 16 52 34" src="https://user-images.githubusercontent.com/63935349/177581442-4bcc179d-f775-4eca-a11d-9c06213fa0ab.png">

However, this breaks all other Webstorm remote interpreter features (such as `npm install`), since we took away the information where to find the `npm` executable. So this is not a fix or workaround, but merely a way to confirm the plugin problem.

**Expected behavior:**
The expected behavior is that the plugin will ignore the `npm` input from the remote interpreter settings and constructs the `nx` commands without using `npm`

**Comment by iguissouma** [comment]
Hello 
I tried a fix, working with my configuration:

<img width="1510" alt="Screenshot 2022-07-07 at 21 29 19" src="https://user-images.githubusercontent.com/9085108/177858119-97582051-86c8-4403-bffa-cb6e5d06722e.png">


can you please test with this version?
>Install plugin from disk

[Nx Console Idea-0.47.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/9066873/Nx.Console.Idea-0.47.0.zip)

**Comment by jpv-os** [comment]
Thanks, will report back soon

**Comment by jpv-os** [comment]
I finally had a chance to try it, but the problem remains. New plugin version and same configuration, does not work. Both running a generator by right clicking => New Component, as well as running a NX Task like you showed in your Run/Debug Configurations screen. The generated command shown in the Run log still looks like screenshot 3.

**Comment by iguissouma** [comment]
Can you take me a screenshot of the version of plugin installed?
<img width="987" alt="Screenshot 2022-07-18 at 14 05 12" src="https://user-images.githubusercontent.com/9085108/179517563-92838982-60a6-4a81-952a-eca6881fd73b.png">

**Comment by jpv-os** [comment]
Installed plugin version:

<img width="985" alt="Bildschirmfoto 2022-07-19 um 11 53 31" src="https://user-images.githubusercontent.com/63935349/179722970-3a62c014-6540-44e2-9475-38d57b20fe55.png">

Nx DevTools settings:

<img width="987" alt="Bildschirmfoto 2022-07-19 um 11 53 44" src="https://user-images.githubusercontent.com/63935349/179723023-5c2749a2-b40d-449b-bd15-e9dc935ad1c4.png">

Remote interpreter settings:

<img width="981" alt="Bildschirmfoto 2022-07-19 um 11 55 35" src="https://user-images.githubusercontent.com/63935349/179723201-2b730033-447a-4155-bda4-52bf4650a6f2.png">

Using the plugin to create a component yields the invalid command (containing call to npm):

<img width="1490" alt="Bildschirmfoto 2022-07-19 um 11 54 21" src="https://user-images.githubusercontent.com/63935349/179723368-fafc4261-3e30-48e7-a073-bb9d760412f3.png">

**Comment by iguissouma** [comment]
Hello, what if you use this path for npm?

<img width="987" alt="Screenshot 2022-07-19 at 13 14 10" src="https://user-images.githubusercontent.com/9085108/179747984-5e103755-e1d4-40ea-9c1d-741510a4df5c.png">

**Comment by iguissouma** [comment]
I understand more the problem, I will try to fix it.
I need to find the npx path based on the path of project manager...

**Comment by jpv-os** [comment]
Thank you very much

**Comment by iguissouma** [comment]
I tried a new workaround using npm run scripts.
I thinks it's the only easy way for now as I can't execute with the path of npx...

<img width="1038" alt="Screenshot 2022-07-21 at 09 47 49" src="https://user-images.githubusercontent.com/9085108/180173607-23cfb0b0-a3d0-477a-82a0-3cf00c6c6822.png">

please try this new version and confirm if it's working.
[Nx Console Idea-0.47.1.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/9157847/Nx.Console.Idea-0.47.1.zip)

**Comment by jpv-os** [comment]
I installed the official release and my problem was fixed. Thank you very much!
