### ISSUE TITLE
Override schematics

### ISSUE THREAD

**Issue by richardsengers** [iguissouma/nx-console-idea-plugin#97]
**Describe the bug:**
When you change the default schematics for the generators in nx.json, for example 
```
"generators": {
"@nrwl/angular:component": {
      "style": "scss",
      "inlineStyle": true,
      "changeDetection": "OnPush",
      "skipTests": true,
      "displayBlock": true
    }
}
```
the properties are not set within the generate panel

<img width="665" alt="generator" src="https://user-images.githubusercontent.com/810038/182348284-3b0c5ccb-eedb-4c97-8284-f1f9a90cac4c.PNG">

**Expected behavior:**
I would expect the checkboxes of displayBlock, skipTests and inlineStyle would have been checked

**Comment by iguissouma** [comment]
It seems an issue with boolean values, I will try to fix it.

**Comment by theorlovsky** [comment]
what about the default values from `schema.json`? we've got custom schematics, and let's say there is some property:

```json
{
  "$schema": "http://json-schema.org/schema",
  "cli": "nx",
  ...
  "properties": {
    "someProperty": {
      "type": "boolean",
      "default": true
    }
  }
}
```

in the plugin it won't be checked by default

**Comment by iguissouma** [comment]
@theorlovsky you are right something wrong for booleans from schema.json too.
I will push a version that could correct this.

**Comment by theorlovsky** [comment]
works for me on 0.48.1 👍

**Comment by iguissouma** [comment]
@richardsengers  I think the problem is solved.

**Comment by richardsengers** [comment]
Yes, it works ....thank you
